config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => APP_CONFIG['host_url']

  root 'welcome#index'

  get 'home_gauge/index'
  get 'home_gauge/:id' => 'home_gauge#show'
  get 'home_gauge/:part/:id' => 'home_gauge#show'

  post 'newsletter' => 'welcome#newsletter'
  post 'request_inspection' => 'welcome#request_inspection'
  get 'company' => 'company#index'
  get 'franchise' => 'franchise#index'
  post 'franchise_contact' => 'franchise#contact', as: :franchise_contact
  get 'geo_owners_search' => 'welcome#get_zees'
  get 'geo_owners_switch' => 'welcome#switch_zees'
  post 'geo_owner_chosen' => 'welcome#multi_zee_selected'
  get 'request_inspection_links' => 'welcome#request_inspection_links'
  resources :resources, :only => [:index,:show]
  resources :agents, :only => [:index,:show]
  resources :buyers, :only => [:index,:show]
  resources :sellers, :only => [:index,:show]

  get 'bbp' => 'bbp#index'
  get 'bbp/success' => 'bbp#success'
  get 'bbp/error' => 'bbp#error'
  get 'bbp/submit' => 'bbp#submit'

end

app/helpers/franchise_helper.rb
module FranchiseHelper
end

app/views/franchise/_big_header.html.erb
<section class="franchise-header">
  <div class="franchise-header__image" style="background-image: url(https://s3-us-west-2.amazonaws.com/hm-com/static/EbWbBxpuc30KuCRgGVlLCg/ken-cardgame.jpg);">
    <h1 class="franchise-header__title">SUCCESS STARTS WITH A VISION</h1>
  </div>
</section>

app/views/franchise/_contact.html.erb
<section class="franchise-contact">
  <div class="franchise-contact__background" style="background-image: url(https://s3-us-west-2.amazonaws.com/hm-com/static/EbWbBxpuc30KuCRgGVlLCg/franchiseop-boat.png);">
    <div class="col-xs-12 col-sm-9 center-block">
      <h2 class="text-center franchise-contact__title">LEARN MORE ABOUT OWNING YOUR OWN BUSINESS</h2>
      <hr class="franchise-contact__breaker">
      <div class="col-xs-12 no-gutters">

        <div class="col-sm-12 col-md-4 franchise-contact-info">
          <div class="col-xs-12 col-sm-6 col-md-12">
            <h3 class="franchise-contact-info__title">Contact Info</h3>
            <p class="franchise-contact-info__street">422 N 300 W</p>
            <p class="franchise-contact-info__city-state-zip">Salt Lake City, UT 84103</p>
            <p class="franchise-contact-info__phone"><a href="tel:801-503-9230">801.503.9230</a></p>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-12">
            <p class="franchise-contact-info__email"><a href="mailto:franchise@housemaster.com">franchise@housemaster.com</a></p>
            <p class="franchise-contact-info__url"><%= link_to "housemaster.com", root_url %></p>
          </div>
        </div>

        <div class="col-sm-12 col-md-8 sections franchise-contact-form">
          <div class="thanks hidden">
            <p class="franchise-contact-form__thanks">
              Thank you for contacting us. One of our representatives will be contacting you shortly.
            </p>
          </div>
          <%= form_for @franchise_contact, :url => franchise_contact_path, :html => {:id => 'ajax-franchise-opportunity'} do |f| %>
            <div class="col-xs-12 col-sm-6">
              <%= f.text_field :name, :placeholder => "NAME", :class => 'franchise-contact-form__name' %>
            </div>
            <div class="col-xs-12 col-sm-6">
              <%= f.text_field :email, :placeholder => "EMAIL", :class => 'franchise-contact-form__email' %>
            </div>
            <div class="col-xs-12">
              <%= f.text_area :message, :placeholder => "MESSAGE", :class => 'franchise-contact-form__message' %>
            </div>
            <div class="col-xs-12">
              <%= f.submit "SEND", :class => 'franchise-contact-form__submit' %>
              <span class="franchise-contact-form__error error-message">&nbsp;</span>
            </div>
            <div class="col-xs-12 franchise-contact-form__loader loading hidden"></div>
          <% end %>
        </div>

      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</section>

app/views/franchise/_nav.html.erb
<nav class="franchise-nav">
  <a class="franchise-nav__logo" href="<%= root_path %>"><img src="https://s3-us-west-2.amazonaws.com/hm-com/static/EbWbBxpuc30KuCRgGVlLCg/nav-logo.png"></a>
</nav>

app/views/franchise/_testimonials.html.erb
<section class="franchise-testimonials">
  <div style="background-image: url(https://s3-us-west-2.amazonaws.com/hm-com/static/EbWbBxpuc30KuCRgGVlLCg/testimonials-green.jpg);" class="franchise-testimonials__image">
    <div class="franchise-testimonials-slider">
      <div class="slide-group">

        <div class="franchise-testimonials-slider-slide active">
          <h3 class="franchise-testimonials-slider-slide__quote">
            "The HouseMaster system stands head and shoulders above the others making me look good and making me money!"<br><strong>- Richard Grunder, HouseMaster Owner</strong>
          </h3>
        </div>
        <!-- <div class="franchise&#45;testimonials&#45;slider&#45;slide"> -->
        <!--   <h3 class="franchise&#45;testimonials&#45;slider&#45;slide__quote"> -->
        <!--     "The HouseMaster system stands head and shoulders above the others making me look good and making me money!"<br><strong>&#45; Richard Grunder, HouseMaster Owner</strong> -->
        <!--   </h3> -->
        <!-- </div> -->
        <!-- <div class="franchise&#45;testimonials&#45;slider&#45;slide"> -->
        <!--   <h3 class="franchise&#45;testimonials&#45;slider&#45;slide__quote"> -->
        <!--     "The HouseMaster system stands head and shoulders above the others making me look good and making me money!"<br><strong>&#45; Richard Grunder, HouseMaster Owner</strong> -->
        <!--   </h3> -->
        <!-- </div> -->

      </div>
      <div class="franchise-testimonials-slider-nav im-a-slider-nav" data-target="franchise-testimonials-slider">
        <ul class="bullets franchise-testimonials-slider-nav-bullets">
          <li class="bullet active">1</li>
          <!-- <li class="bullet">2</li> -->
          <!-- <li class="bullet">3</li> -->
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/franchise/_we_are.html.erb
<section class="franchise-we-are">
  <h2 class="text-center franchise-we-are__title">We Are HouseMaster</h2>
  <hr class="franchise-we-are__breaker">
  <div class="col-xs-12 col-sm-8 center-block">
    <div class="col-sm-12 col-md-4 franchise-we-are-description">
      <h3 class="franchise-we-are-description__title">Be Supported</h3>
      <p class="franchise-we-are-description__text">
        HouseMaster offers a trusted name in the community. The HouseMaster name offers you the support of the brand and the entire HouseMaster team. We will work hard to provide you with the tools you need; and you'll work hard to provide your customers with the knowledge they want.
      </p>
    </div>
    <div class="col-sm-12 col-md-4 franchise-we-are-description">
      <h3 class="franchise-we-are-description__title">Be Confident</h3>
      <p class="franchise-we-are-description__text">
        With HouseMaster on your side you'll find the confidence you need to succeed as an entrepreneur. We get it - owning a business can be stressful. But we're here to help. With our team behind you, you'll find the confidence to build your business.
      </p>
    </div>
    <div class="col-sm-12 col-md-4 franchise-we-are-description">
      <h3 class="franchise-we-are-description__title">Be Successful</h3>
      <p class="franchise-we-are-description__text">
        Your success is our success, and when you join the HouseMaster family, your achievement becomes our priority. We're here to help you attain the income you want, the independence you've been searching for, and a legacy to be proud of.
      </p>
    </div>
  </div>
  <div class="clearfix"></div>
</section>

app/views/franchise/_we_do.html.erb
<section class="franchise-we-do">
  <h2 class="text-center franchise-we-do__title">What We Do</h2>
  <hr class="franchise-we-do__breaker">
  <div class="col-xs-12 col-sm-8 center-block">
    <p class="col-xs-12 franchise-we-do__text">
      For the past 35 years, HouseMaster has been helping people from all educational and business backgrounds realize their dreams of business ownership, while helping buyers make educated, informed decisions about their home purchases. Our goal is to help you, the business owner, as well as your customers feel the trust, condence and, ultimately, the success that can come with the HouseMaster experience.
    </p>
    <div class="col-xs-12 franchise-we-do__tags">
      <button class="franchise-we-do__tag">TAG CATEGORY</button>
      <button class="franchise-we-do__tag active">TAG CATEGORY</button>
    </div>
    <div class="col-xs-12 no-gutters">
      <div class="col-xs-12 col-sm-6 col-md-4 franchise-we-do-media">
        <div class="franchise-we-do-media__image"></div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4 franchise-we-do-media">
        <div class="franchise-we-do-media__video" data-toggle="modal" data-target="#video1-modal">
          <div class="franchise-we-do-media__play">
            <i class="glyphicon glyphicon-play"></i>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4 franchise-we-do-media">
        <div class="franchise-we-do-media__video" data-toggle="modal" data-target="#video2-modal">
          <div class="franchise-we-do-media__play">
            <i class="glyphicon glyphicon-play"></i>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4 franchise-we-do-media">
        <div class="franchise-we-do-media__image"></div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4 franchise-we-do-media">
        <div class="franchise-we-do-media__image"></div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
</section>
<!-- video modals -->
<div id="video1" class="modal-override">
  <div class="modal fade" id="video1-modal" tabindex="-1" role="dialog" aria-labelledby="video1-modal-label">
    <div class="modal-dialog modal-lg modal-override__document" role="document">
      <button type="button" class="close modal-override__close close modal-override__close--light" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="modal-override__content">
        <video id="video1Video" controls="" style="width: 100%; height: 100%;">
          <source src="https://s3.amazonaws.com/hm_conference/2014/video/video1.mp4" type="video/mp4">
          <source src="https://s3.amazonaws.com/hm_conference/2014/video/video1.webm" type="video/webm">
          <source src="https://s3.amazonaws.com/hm_conference/2014/video/video1.ogv" type="video/ogg">
          fallback
          <p>Your browser does not support video, please update your browser.</p>
        </video>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<div id="video2" class="modal-override">
  <div class="modal fade" id="video2-modal" tabindex="-1" role="dialog" aria-labelledby="video2-modal-label">
    <div class="modal-dialog modal-lg modal-override__document" role="document">
      <button type="button" class="close modal-override__close close modal-override__close--light" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div class="modal-override__content">
        <video id="video2Video" controls="" style="width: 100%; height: 100%;">
          <source src="https://s3.amazonaws.com/hm_conference/2014/video/video2.mp4" type="video/mp4">
          <source src="https://s3.amazonaws.com/hm_conference/2014/video/video2.webm" type="video/webm">
          <source src="https://s3.amazonaws.com/hm_conference/2014/video/video2.ogv" type="video/ogg">
          fallback
          <p>Your browser does not support video, please update your browser.</p>
        </video>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<!-- /video modals -->

app/views/franchise/index.html.erb
<div class="row no-gutters">
  <div class="col-xs-12 no-gutters">
    <%= render :partial => 'we_are' %>
  </div>
</div>

<div class="row no-gutters">
  <div class="col-xs-12 no-gutters">
    <%= render :partial => 'we_do' %>
  </div>
</div>

<div class="row no-gutters">
  <div class="col-xs-12 no-gutters">
    <%= render :partial => 'testimonials' %>
  </div>
</div>

<div class="row no-gutters">
  <div class="col-xs-12 no-gutters">
    <%= render :partial => 'contact' %>
  </div>
</div>