config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => APP_CONFIG['host_url']

  root 'welcome#index'

  get 'home_gauge/index'
  get 'home_gauge/:id' => 'home_gauge#show'
  get 'home_gauge/:part/:id' => 'home_gauge#show'

  post 'newsletter' => 'welcome#newsletter'
  post 'request_inspection' => 'welcome#request_inspection'
  get 'company' => 'company#index'
  get 'franchise' => 'franchise#index'
  post 'franchise_contact' => 'franchise#contact', as: :franchise_contact
  get 'geo_owners_search' => 'welcome#get_zees'
  get 'geo_owners_switch' => 'welcome#switch_zees'
  post 'geo_owner_chosen' => 'welcome#multi_zee_selected'
  get 'request_inspection_links' => 'welcome#request_inspection_links'
  resources :resources, :only => [:index,:show]
  resources :agents, :only => [:index,:show]
  resources :buyers, :only => [:index,:show]
  resources :sellers, :only => [:index,:show]

  get 'bbp' => 'bbp#index'
  get 'bbp/success' => 'bbp#success'
  get 'bbp/error' => 'bbp#error'
  get 'bbp/submit' => 'bbp#submit'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # layout :resolve_layout
  layout 'home'
  before_filter :zee_sidebar, :only => [:get_zees]

  def index
    @home_header = Resource.get_articles([8,9,10])
    @image_slider_articles = Resource.get_articles([5,11])
  end

  def request_inspection
    # save form submission (and return errors if any)
    request = RequestInspection.new({
      "name" => params[:name],
      "phone" => params[:phone],
      "email" => params[:email],
      "zip_code" => (params[:zip_code]) ? params[:zip_code] : @geolocation['postal']
    })

    # if errors with saving, return errors else continue
    if request.save
      # if zee results show multiple and user selected one, use that else default to first
      i = (session[:widget]['selected']) ? session[:widget]['selected'].to_i : 0
      frannum = (session[:widget]['zees'][i]['franchisee_number']) ? session[:widget]['zees'][i]['franchisee_number'] : '009999' # default to 009999 if no zee number exists for zee widget

      # default from email = request@housemaster.com
      from = "#{APP_CONFIG['forms']['request_inspection']['from']}"
      # default to email = hminfo@housemaster.com
      to = "#{APP_CONFIG['forms']['request_inspection']['to']}"
      # default bcc = hminfo@housemaster.com, it+housemaster@sopraservices.com
      bcc = "#{APP_CONFIG['forms']['request_inspection']['bcc']}"

      # get the current franchisee email from widget session if zee is in area
      if session[:widget]['zees'][i]['email']
        # to becomese zee's email
        to = session[:widget]['zees'][i]['email']
      end

      # send email message to zee
      NotificationsMailer.inspection_request({
        "from" => from,
        "to" => to,
        "bcc" => bcc,
        "name" => request.name,
        "email" => request.email,
        "zip_code" => request.zip_code,
        "phone" => request.phone
      }).deliver

      # then send thank you email to customer
      to = request.email
      # default from email = request@housemaster.com
      from = "#{APP_CONFIG['forms']['request_inspection']['from']}"

      # send email message to zee
      NotificationsMailer.request_inspection_thanks({
        "from" => from,
        "to" => to
      }).deliver

      # return success json with thank you message (which will replace form with 'thanks!')
      render :json => {:success => "Thanks! Your request has been sent. We look forward to serving you real soon."}.to_json, :status => 200
    else
      # wasn't able to save request, send error
      render :json => {:error => "An unknown error has occurred, please try again later."}.to_json, :status => 400
    end
  end

  def newsletter
    # email newsletter subscribe form submit
    # if zee results show multiple and user selected one, use that else default to first
    i = (session[:widget]['selected']) ? session[:widget]['selected'].to_i : 0
    # need to pass the following data over
    data = Newsletter.new({
      "first_name" => params[:first_name],
      "last_name" => params[:last_name],
      "email" => params[:email],
      "frannum" => (session[:widget]['zees'][i]['franchisee_number']) ? session[:widget]['zees'][i]['franchisee_number'] : '009999', # default to 009999 if no zee number exists for zee widget
      "source" => 'hmwebsite', # where this newsletter subscription came from
      "zip" => (@geolocation['postal']) ? @geolocation['postal'] : ''
    })

    # if errors with saving, return errors else continue
    if data.save
      # api call requires this format
      data = {:data => data.to_json}
      p 'sending request to NJ servers'
      response = ApiCall.post(APP_CONFIG['forms']['newsletter'], data)
      body = JSON.parse(response.body)
      # p 'response.code'
      # p response.code
      # p 'JSON.parse(response.body)'
      # p body
      if response.code == "200" || response.code == "400"
        render :json => body.to_json, :status => response.code
      end
    else
      # return saving error
      render :json => {:error => data.errors.full_messages.to_sentence}.to_json, :status => 400
    end
  end
  
  def multi_zee_selected
    if session[:widget] && params['selected']
      session[:widget]['selected'] = params['selected'].to_i
      render :json => {:success => 'selected franchise owner set'}.to_json, :status => 200
    else
      render :json => {:error => 'unable to select a franchise owner'}.to_json, :status => 400
    end
  end

  def get_zees
    # AJAX calls here to get franchisee territory info for this area from Inertia API
    # if session widget data already set and not expired, use that
    if !params['reset'] && @widget_session_check
      session[:widget_expire] = Time.current.to_s
      render :html => get_zee_html(session[:widget])
    elsif params['city'].empty? || params['state'].empty?
      # no need to ping API, just return "no one in your area"
      session[:widget] = {}
      session[:widget_expire] = Time.current.to_s
      render :html => get_zee_html(session[:widget])
    else
      session[:widget] = nil
      session[:widget_expire] = nil
      call = ApiCall.get("#{APP_CONFIG['inertia']['url']}/api/v1/get_zees?city=#{params['city']}&state=#{params['state']}", "#{APP_CONFIG['inertia']['user_key']}:#{APP_CONFIG['inertia']['account_key']}")
      body = JSON.parse(call.body)
      if call.code == "200"
        # Include city/zip in response
        response = {
          'zees' => []
        }
        if body.count > 0
          body.each do |r|
            response['zees'] << r
          end
        end
        response['location'] = {
          'city' => params['city'].gsub(/\w+/, &:capitalize),
          'state' => params['state'].upcase
        }
        # render :json => response.to_json, :status => 200
        session[:widget] = response
        # see raw results from Inertia
        if Rails.env == 'development'
          p '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
          p session[:widget]
          p '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
        end
        session[:widget_expire] = Time.current.to_s
        render :html => get_zee_html(session[:widget])
      else
        render :json => {:error => 'Unable to query territories'}.to_json, :status => 400
      end
    end
  end

  def switch_zees
    # AJAX calls here to switch city/state and then 
    # search for franchisee territory info
    query_string = "location=#{params['location']}"
    # TODO, make sure we validate that location param not only returns city/state, 
    #       but also confirms that city/state exist
    call = ApiCall.get("#{APP_CONFIG['inertia']['url']}/api/v1/valid_location_check?#{query_string}", "#{APP_CONFIG['inertia']['user_key']}:#{APP_CONFIG['inertia']['account_key']}")
    body = JSON.parse(call.body)
    if call.code == "200" || call.code == "400"
      render :json => body.to_json, :status => call.code
    else
      render :json => {:error => 'Unable to search for location'}.to_json, :status => 400
    end
  end

  def request_inspection_links
    target = "" # will only change if ISN link found
    footer_css_class = "footer-nav__btn"
    widget_css_class = "btn accordion-nav owner-contact__schedule--btn"
    # determin default link, class and onclick based on if this is home page or not
    if params['page'] == root_path
      link = "#{root_path(:anchor => 'request_inspection')}"
      top_css_class = "collapse-mobile word-wrap"
    else
      link = '#request-inspection'
      top_css_class = "collapse-mobile accordion-nav word-wrap"
      onclick = "accordionTrigger(this)"
    end
    if @geo_zees
      if @geo_zees['zees'].count == 1
        # if there is only 1 zee, that becomes selected
        # if current/selected zee has isn_link, us that, else use default
        if @geo_zees['zees'][0]['links'].has_key?('isn_url')
          link = @geo_zees['zees'][0]['links']['isn_url']
          target = "_blank"
          onclick = ""
        end
      elsif @geo_zees['zees'].count > 1 && @geo_zees['selected']
        # if multiple zees and one is already selected
        # if one zee is selected and has isn_link, update to that
        if @geo_zees['zees'][@geo_zees['selected']]['links'].has_key?('isn_url')
          link = @geo_zees['zees'][@geo_zees['selected']]['links']['isn_url']
          target = "_blank"
          onclick = ""
        end
      end
    end

    render :json => {
      "top_link" => "<a class='#{top_css_class}' href='#{link}' target='#{target}' onclick='#{onclick}'>REQUEST <br />INSPECTION</a>".html_safe,
      "footer_link" => "<a class='#{footer_css_class}' href='#{link}' target='#{target}' onclick='#{onclick}'>REQUEST AN APPOINTMENT</a>".html_safe,
      "multi_widget_link" => "<a class='#{widget_css_class}' href='#{link}' target='#{target}' onclick='#{onclick}'>REQUEST AN INSPECTION</a>".html_safe
    }.to_json, :status => 200
  end

  private

  def get_zee_html(zees)
    @current_page = params['page']
    @geo_zees = zees
    # generate/return the zee sidenav html content
    return render_to_string( :partial => "_shared/widget/load_content", :layout => false ).html_safe
  end

  # Need way to easily change layout used for specific actions
  # http://stackoverflow.com/a/3025806/1180523
  def resolve_layout
    case action_name
    when "index"
      "home"
    else
      "application"
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_big_green_header.html.erb
<section class="homehero">
  <div class="homehero-slider">
    <div class="slide-group">
      <% i = 0 %>
      <% @home_header.each do |slide| %>
        <div class="homehero-slider-slide homehero-slider-slide--img <%= (i == 0) ? 'active' : '' %>" style="background-image: url(<%= slide['header_image_home'] %>)">
          <h1 class="col-md-offset-1 col-md-4 homehero-slider-slide__title">
            <%= link_to slide['title'], "#{root_url}#{slide['slug']}" %>
          </h1>
        </div>
        <% i = i + 1 %>
      <% end %>
    </div>
  </div>
  <div class="col-md-offset-5 col-md-6 homehero-slider homehero-slider--overlay">
    <div class="slide-group">
      <% i = 0 %>
      <% @home_header.each do |slide| %>
        <div class="homehero-slider-slide <%= (i == 0) ? 'active' : '' %>">
          <hr class="homehero-slider-slide__breaker">
          <p class="homehero-slider-slide__text">
            <%= link_to slide['seo_description'], "#{root_url}#{slide['slug']}" %>
          </p>
          <hr class="homehero-slider-slide__breaker">
          <p class="homehero-slider-slide__topic"><%= slide['seo_keywords'] %></p>
        </div>
        <% i = i + 1 %>
      <% end %>
    </div>
    <div class="homehero-slider-nav im-a-slider-nav" data-target="homehero-slider">
      <ul class="bullets homehero-slider-nav-bullets">
        <% for ii in 1..i %>
          <li class="bullet <%= (ii == 1) ? 'active' : '' %>">
            <%= ii %>
          </li>
        <% end %>
      </ul>
      <span class="arrows homehero-slider-nav__arrow--next" data-direction="next">&gt;</span>
      <span class="arrows homehero-slider-nav__arrow--prev" data-direction="prev">&lt;</span>
    </div>
  </div>
</section>

app/views/welcome/_lego_blocks.html.erb
<section class="lego-blocks">
  <div class="col-xs-12 col-sm-4 lego-block">
    <div class="lego-block__circle"></div>
    <h3 class="lego-block__title"><%= link_to 'BUYERS', buyers_path  %></h3>
    <p class="lego-block__text">Purchasing a home? We can help.</p>
  </div>
  <div class="col-xs-12 col-sm-4 lego-block">
    <div class="lego-block__circle"></div>
    <h3 class="lego-block__title"><%= link_to 'SELLERS', sellers_path  %></h3>
    <p class="lego-block__text">Let's help you sell your home.</p>
  </div>
  <div class="col-xs-12 col-sm-4 lego-block">
    <div class="lego-block__circle"></div>
    <h3 class="lego-block__title"><%= link_to 'AGENTS', agents_path  %></h3>
    <p class="lego-block__text">Secret service? We can help with that too.</p>
  </div>
</section>

app/views/welcome/_services_slider.html.erb
<section class="col-md-12 home-services">
  <aside class="home-services-offcanvas home-services-offcanvas--inline-block <%#= 'active' # for slide out %>">
    <div class="home-services-slider-nav home-services-slider-nav--offcanvas im-a-slider-nav" data-target="home-services-slider">
      <div class="home-services-slider-nav__bullet-list home-services-offcanvas__inline-block">
        <ul class="bullets home-services-slider-nav-bullets">
          <li class="home-services-slider-nav-bullets__title">INSPECTION SERVICES</li>

          <li class="bullet home-services-slider-nav-bullets__link active">ROOFING</li>
          <li class="bullet home-services-slider-nav-bullets__link">HEATING & COOLING</li>
          <li class="bullet home-services-slider-nav-bullets__link">PLUMBING</li>
          <li class="bullet home-services-slider-nav-bullets__link">SIDING</li>
          <li class="bullet home-services-slider-nav-bullets__link">STRUCTURE</li>
          <li class="bullet home-services-slider-nav-bullets__link">FOUNDATION</li>
          <li class="bullet home-services-slider-nav-bullets__link">ELECTRICAL</li>
          <li class="bullet home-services-slider-nav-bullets__link">KITCHEN</li>

          <li class="home-services-slider-nav-bullets__title">ADDITIONAL SERVICES</li>

          <li class="bullet home-services-slider-nav-bullets__link">RADON SCREENING</li>
          <li class="bullet home-services-slider-nav-bullets__link">WOOD DESTROYING INSECTS</li>
          <li class="bullet home-services-slider-nav-bullets__link">LEAD PAINT SCREENING</li>
          <li class="bullet home-services-slider-nav-bullets__link">WATER POTABILITY</li>
          <li class="bullet home-services-slider-nav-bullets__link">POOL</li>
          <li class="bullet home-services-slider-nav-bullets__link">WATER AND WASTE</li>
          <li class="bullet home-services-slider-nav-bullets__link">EIFS</li>
          <li class="bullet home-services-slider-nav-bullets__link">MOLD TESTING</li>
          <li class="bullet home-services-slider-nav-bullets__link">NEW CONSTRUCTION</li>
          <li class="bullet home-services-slider-nav-bullets__link">COMMERCIAL PROPERTY</li>
          <li class="bullet home-services-slider-nav-bullets__link">PREVENTATIVE MAINTENANCE</li>
        </ul>
        <div id="services-arrows" class="home-services-slider-nav--arrows">
          <span class="arrows prev home-services-slider-nav__arrow--prev hidden" data-direction="prev" data-hide-when="true">&lt;</span>
          <span class="arrows next home-services-slider-nav__arrow--next" data-direction="next" data-hide-when="true">&gt;</span>
        </div>
      </div>
      <div id="services-toggle" class="home-services-offcanvas-toggle home-services-offcanvas__inline-block active">
        <!-- <span class="">=</span> -->
        <span class="home-services-offcanvas-toggle__btn glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
      </div>
    </div>
  </aside>
  <div class="home-services-slider home-services__inline-block">
    <div class="slide-group">
      <%= render :partial => 'slides_services' %>
      <%= render :partial => 'slides_additional_services' %>
      <%# one dummy slide at end %>
      <div class="home-services-slider-slide last">
        <div class="home-services-slider-slide__section--top"></div>
        <div class="home-services-slider-slide__section--middle">
          <div class="col-md-12"></div>
        </div>
        <div class="home-services-slider-slide__section--bottom">
          <div class="col-md-12"></div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_slider_2_col.html.erb
<section class="homeintro">
  <div class="hidden-xs col-sm-6 no-gutters homeintro-slider">
    <div class="slide-group">
      <% i = 0 %>
      <% @image_slider_articles.each do |slide| %>
        <div class="homeintro-slider-slide homeintro-slider-slide--img <%= (i == 0) ? 'active' : '' %>">
          <div class="homeintro-slider-slide__graphic" style="background-image: url(<%= slide['article_image'] %>);"></div>
        </div>
        <% i = i + 1 %>
      <% end %>
    </div>
  </div>
  <div class="col-sm-6 no-gutters homeintro-slider">
    <div class="slide-group">
      <% i = 0 %>
      <% @image_slider_articles.each do |slide| %>
        <div class="homeintro-slider-slide <%= (i == 0) ? 'active' : '' %>">
          <h2 class="homeintro-slider-slide__title"><%= link_to slide['title'], "#{root_url}#{slide['slug']}" %></h2>
          <p class="homeintro-slider-slide__desc"><%= slide['seo_description'] %></p>
        </div>
        <% i = i + 1 %>
      <% end %>
    </div>
    <div class="homeintro-slider-nav im-a-slider-nav" data-target="homeintro-slider">
      <ul class="bullets homeintro-slider-nav-bullets">
        <% for ii in 1..i %>
          <li class="bullet <%= (ii == 1) ? 'active' : '' %>">
            <%= ii %>
          </li>
        <% end %>
      </ul>
      <span class="arrows homeintro-slider-nav__arrow--next" data-direction="next">&gt;</span>
      <span class="arrows homeintro-slider-nav__arrow--prev" data-direction="prev">&lt;</span>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<div class="row no-gutters">
  <%= render :partial => 'slider_2_col' %>
</div>

<div class="row no-gutters">
  <%= render :partial => 'lego_blocks' %>
</div>

<div class="row no-gutters">
  <%= render :partial => '_shared/sliders/featured_articles' %>
</div>

<span id="services" class="anchor-id"></span>
<div class="row no-gutters">
  <%= render :partial => 'services_slider' %>
</div>

<span id="request_inspection" class="anchor-id"></span>
<div class="row no-gutters">
  <%= render :partial => '_shared/forms/request_inspection' %>
</div>