config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => APP_CONFIG['host_url']

  root 'welcome#index'

  get 'home_gauge/index'
  get 'home_gauge/:id' => 'home_gauge#show'
  get 'home_gauge/:part/:id' => 'home_gauge#show'

  post 'newsletter' => 'welcome#newsletter'
  post 'request_inspection' => 'welcome#request_inspection'
  get 'company' => 'company#index'
  get 'franchise' => 'franchise#index'
  post 'franchise_contact' => 'franchise#contact', as: :franchise_contact
  get 'geo_owners_search' => 'welcome#get_zees'
  get 'geo_owners_switch' => 'welcome#switch_zees'
  post 'geo_owner_chosen' => 'welcome#multi_zee_selected'
  get 'request_inspection_links' => 'welcome#request_inspection_links'
  resources :resources, :only => [:index,:show]
  resources :agents, :only => [:index,:show]
  resources :buyers, :only => [:index,:show]
  resources :sellers, :only => [:index,:show]

  get 'bbp' => 'bbp#index'
  get 'bbp/success' => 'bbp#success'
  get 'bbp/error' => 'bbp#error'
  get 'bbp/submit' => 'bbp#submit'

end

app/controllers/bbp_controller.rb
class BbpController < ApplicationController
  layout = 'bbp'

  def index
    @subscriber = params["sE"]
    @account = params["sU"]
    @list = params["sId"]

    p params["subscribe"]
    if params["subscribe"] == "yes"
      submit(@subscriber, @account, @list)
    end
  end

  def success
  end

  def error
  end

  def submit(subscriber, account, list)
    uri = URI.parse("http://housemaster.us11.list-manage.com/profile/post")

    http = Net::HTTP.new(uri.host, uri.port)

    request = Net::HTTP::Post.new(uri.request_uri)
    request.set_form_data({"e" => subscriber, "u" => account, "id" => list, "MERGE3" => "yes"})

    response = http.request(request)
    if response.code == "200"
      redirect_to bbp_success_path
    else
      redirect_to bbp_error_path
    end
  end
end

app/helpers/bbp_helper.rb
module BbpHelper
end

app/views/bbp/error.html.erb
<h1 class="welcome__title">An unknown error occurred...</h1>
<p class="welcome__text">Please try again, if this persists please contact your inspector</p>

app/views/bbp/index.html.erb
<h1 class="welcome__title">The HouseMaster Buyer Benefits Program</h1>
<p class="welcome__text">
  can help you save hundreds or even thousands of dollars on the things you need as you move into your new home.
  <br>
  Subscribe below to start receiving these great benefits!
</p>

<%= link_to bbp_path+"?sU=#{@account}&sId=#{@list}&sE=#{@subscriber}&subscribe=yes" do %><button class="welcome__subscribe-btn">Subscribe!</button><% end %>

<div class="welcome-videos">
  <iframe class="welcome-videos__bbp" src="https://player.vimeo.com/video/130228166" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>

app/views/bbp/success.html.erb
<h1 class="welcome__title">Thanks for Subscribing!</h1>
<p class="welcome__text">Check your inbox for all your sweet deals!</p>