config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => APP_CONFIG['host_url']

  root 'welcome#index'

  get 'home_gauge/index'
  get 'home_gauge/:id' => 'home_gauge#show'
  get 'home_gauge/:part/:id' => 'home_gauge#show'

  post 'newsletter' => 'welcome#newsletter'
  post 'request_inspection' => 'welcome#request_inspection'
  get 'company' => 'company#index'
  get 'franchise' => 'franchise#index'
  post 'franchise_contact' => 'franchise#contact', as: :franchise_contact
  get 'geo_owners_search' => 'welcome#get_zees'
  get 'geo_owners_switch' => 'welcome#switch_zees'
  post 'geo_owner_chosen' => 'welcome#multi_zee_selected'
  get 'request_inspection_links' => 'welcome#request_inspection_links'
  resources :resources, :only => [:index,:show]
  resources :agents, :only => [:index,:show]
  resources :buyers, :only => [:index,:show]
  resources :sellers, :only => [:index,:show]

  get 'bbp' => 'bbp#index'
  get 'bbp/success' => 'bbp#success'
  get 'bbp/error' => 'bbp#error'
  get 'bbp/submit' => 'bbp#submit'

end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  layout 'company'

  def index
  end

end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/company/_awards.html.erb
<section class="col-xs-12 company-awards">
  <h2 class="company-awards__title">AWARDS</h2>
  <hr class="company-awards__breaker">

  <% hidden = 'show' # hidden = 'hidden toggle' if hidding %>
  <div class="company-awards-award <%= hidden %>">
    <div class="col-xs-3">
      <div style="background-image: url(https://s3-us-west-2.amazonaws.com/hm-com/static/BQx4wiQBT-_H64eYh3cnsQ/top50-2014.jpg);" class="company-awards-award__image"></div>
    </div>
    <div class="col-xs-9">
      <h3 class="company-awards-award__title">2014 FBR'S TOP 50 FRANCHISE</h3>
      <p class="company-awards-award__text">
        Based on a survey of more than 26,000 franchisees representing more than 350 franchise brands, Franchise Business Review's 2014 franchisee satisfaction award-winners includes many familiar faces.
      </p>
    </div>
    <div class="clearfix"></div>
    <hr class="company-awards__breaker">
  </div>
  <div class="company-awards-award <%= hidden %>">
    <div class="col-xs-3">
      <div style="background-image: url(https://s3-us-west-2.amazonaws.com/hm-com/static/BQx4wiQBT-_H64eYh3cnsQ/franchise500.jpg);" class="company-awards-award__image"></div>
    </div>
    <div class="col-xs-9">
      <h3 class="company-awards-award__title">FRANCHISE 500</h3>
      <p class="company-awards-award__text">
        HouseMaster, the nation's first and oldest home inspection franchise, has been named the No. 1 home inspection franchise in Entrepreneur magazine's Franchise 500&reg; for the third straight year.
      </p>
    </div>
    <div class="clearfix"></div>
    <hr class="company-awards__breaker">
  </div>
  <% hidden = 'hidden toggle' # hidden = 'show' if showing %>
  <div class="company-awards-award <%= hidden %>">
    <div class="col-xs-3">
      <div style="background-image: url(https://s3-us-west-2.amazonaws.com/hm-com/static/BQx4wiQBT-_H64eYh3cnsQ/top50-2013.jpg);" class="company-awards-award__image"></div>
    </div>
    <div class="col-xs-9">
      <h3 class="company-awards-award__title">2013 FBR'S TOP 50 FRANCHISE</h3>
      <p class="company-awards-award__text">
        Franchise Business Review looked specifically at responses from franchisees who categorized themselves as "veterans" in the demographics section of the survey-in 2013, that was 2,892 vets.
      </p>
    </div>
    <div class="clearfix"></div>
    <hr class="company-awards__breaker">
  </div>

  <% if hidden != 'show' %>
    <button class="company-awards__show-all show-hide-button" data-target=".company-awards-award.toggle">SHOW ALL</button>
  <% end %>
</section>

app/views/company/_header_intro.html.erb
<section class="company-header">
  <div class="col-md-6 no-gutters company-header__section">
    <div class="company-header__image" style="background-image: url(https://s3-us-west-2.amazonaws.com/hm-com/static/seIPdnmEnsVQEWwsxaxG7g/ken-cardgame.jpg);">
      <h1 class="visible-xs visible-sm company-header-content__title--mobile">THE EVOLUTION</h1>
    </div>
  </div>
  <div class="col-md-6 company-header__section company-header__section--mobile">
    <div class="company-header-content">
      <h1 class="hidden-xs hidden-sm company-header-content__title">THE EVOLUTION</h1>
      <p class="company-header-content__text">
        The HouseMaster home and building inspection franchise system was founded in 1979. Since then, we have grown to over 370 locally owned and operated offices across North America. Our trusted team of inspectors has collectively performed over 2.5 million inspections for prospective homebuyers.
      </p>
    </div>
  </div>
</section>

app/views/company/_header_timeline.html.erb
<section class="visible-lg company-timeline">
  <ul class="company-timeline-events">
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>1971: Entered Home Inspection Business</strong> <br>We are the oldest and most respected name in home and building inspections throughout North America. In 1971, Ken Austin began an independent home inspection company in New Jersey, thus starting the journey that would eventually bring him to HouseMaster.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>1976: Co-Founded ASHI</strong> <br>In 1976 Ken Austin became a founding member of the American Society of Home Inspectors (ASHI), the first industry organization to set standards for home inspections.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>1979: First to Franchise </strong> <br>After developing a successful multi-inspector home inspection business, Ken Austin decided to take his model to the national level. In 1979 he created HouseMaster, the first home inspection franchise operation in the US, which remains the first and oldest home inspection franchise system in North America.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>1984: 1st On-Site Written Report</strong> <br>With the home inspection industry in its infancy, Ken Austin and team developed formalized training procedures for home inspectors - this included standardized, and clearly categorized on-site written inspection reports, pioneering the professional home inspection business.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>1986: 1st Agent Indemnification Program</strong> <br>In 1986 HouseMaster established our Agent Indemnification Program, providing a necessary layer of protection for our agents. At HouseMaster we maintain a comprehensive Limited Repair Reimbursement policy, which provides coverage for referral sources in the event they are sued for recommending us.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>1987: Started NIBI</strong> <br>In 1987 The National Institute of Building Inspectors was created - NIBI would become a premier school for home inspectors, and has been providing home inspection training courses and certifications for the last 26 years.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>1989: Introduces Pre-Inspections</strong> <br>HouseMaster introduced the idea of pre-inspecting your home before accepting an offer or before putting it on the market in 1989 - we have since helped thousands and thousands of customers prepare for the selling process with a pre-inspection.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>1994: Introduced Inspection Guarantee</strong> <br>Taking a step forward ahead of the competition, in 1994 HouseMaster introduced their Inspection Guarantee. The protection the guarantee provides to franchisees as well as inspection customers is a great example of HouseMaster's commitment to excellence.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>1999: Introduced HouseMaster's Hero</strong> <br>In 1999 HouseMaster introduced the official company representative, the "HouseMaster Hero" - this character would be the face of the franchise system for years.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>2000: 1st Online Training Program</strong> <br>HouseMaster started off the new millennium with a bang. In 2000 they took their training program to the internet and started the 1st online training program for home inspectors.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>2002: Became Charter Members of AHIA</strong> <br>HouseMaster's current President, Kathleen Austin Kuhn, daughter of the founder Ken Austin, and a 19-year veteran of the company, became a Charter Member of the American Home Inspection Association (AHIA). AHIA, a non-profit corporation made up of the largest national home inspection companies, is dedicated to shaping the legislative issues facing the home inspection industry, as well as the real estate industry in general.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>2008: Partnered with Sopra Capital</strong> <br>In 2008 HouseMaster began an important partnership with investment firm Sopra Capital, based in Salt Lake City, Utah. The Sopra team brought their resources and expertise and helped HouseMaster continue to build the promising franchise system.
      </p>
    </li>
    <li>
      <div class="company-timeline-events__bullet-image"></div>
      <p class="company-timeline-events__text">
        <strong>2009: 30th Year Anniversary </strong> <br>In 2009 HouseMaster celebrated 30 successful years in the home inspection industry, continuing the vision that Ken started and keeping the culture of family. With the most experienced and professional support staff in the industry the HouseMaster name continues to represent quality and leadership.
      </p>
    </li>
  </ul>
</section>

app/views/company/_media_assets.html.erb
<section class="col-xs-12 company-media">
  <h2 class="company-media__title">MEDIA ASSETS</h2>
  <hr class="company-media__breaker">

  <div class="col-xs-12">
    <h3 class="company-media__subtitle">LOGOS</h3>
  </div>
  <div class="company-media-block col-xs-12 col-sm-6">
    <div class="company-media__logo company-media__logo-white">
      <img src="https://s3-us-west-2.amazonaws.com/hm-com/static/o0APUy3pwy8klymx2sj5EA/HM-Logo_Guarantee2014_White.png">
    </div>
  </div>
  <div class="company-media-block col-xs-12 col-sm-6">
    <div class="company-media__logo company-media__logo-normal">
      <img src="https://s3-us-west-2.amazonaws.com/hm-com/static/o0APUy3pwy8klymx2sj5EA/HM-Logo_Guarantee2014.png">
    </div>
  </div>
  <div class="clearfix"></div>
  <br>
  <!-- <div class="company&#45;media&#45;block col&#45;xs&#45;6 col&#45;sm&#45;4"> -->
  <!--   <div style="background&#45;image: url();" class="company&#45;media__asset"></div> -->
  <!-- </div> -->
  <!-- <div class="company&#45;media&#45;block col&#45;xs&#45;6 col&#45;sm&#45;4"> -->
  <!--   <div style="background&#45;image: url();" class="company&#45;media__asset"></div> -->
  <!-- </div> -->
  <!-- <div class="company&#45;media&#45;block col&#45;xs&#45;6 col&#45;sm&#45;4"> -->
  <!--   <div style="background&#45;image: url();" class="company&#45;media__asset"></div> -->
  <!-- </div> -->
  <!-- <div class="clearfix"></div> -->
  <!-- <br> -->

  <button class="company-media__show-all show-hide-button hidden" data-target=".company-media-block.toggle">SHOW ALL</button>
</section>

app/views/company/_newsroom.html.erb
<section class="col-xs-12 company-news">
  <h2 class="company-news__title">IN THE NEWS</h2>
  <hr class="company-news__breaker">

  <% hidden = 'show' # hidden = 'hidden toggle' if hidding %>
  <div class="company-news-event <%= hidden %>">
    <div class="col-xs-3">
      <div style="background-image: url(https://s3-us-west-2.amazonaws.com/hm-com/static/-yBcMHWspiO86LINSVRfww/ashi.png);" class="company-news-event__image"></div>
    </div>
    <div class="col-xs-9">
      <h3 class="company-news-event__date">January 15, 2016</h3>
      <p class="company-news-event__text">
        Our home inspectors are members of the National Institute of Building Inspectors (NIBI) and the American Society of Home Inspectors (ASHI).
      </p>
    </div>
    <div class="clearfix"></div>
    <hr class="company-news__breaker">
  </div>
  <div class="company-news-event <%= hidden %>">
    <div class="col-xs-3">
      <div style="background-image: url(https://s3-us-west-2.amazonaws.com/hm-com/static/-yBcMHWspiO86LINSVRfww/homesforheroes.png);" class="company-news-event__image"></div>
    </div>
    <div class="col-xs-9">
      <h3 class="company-news-event__date">January 12, 2016</h3>
      <p class="company-news-event__text">
        Heroes in Southwest Michigan access discounts on home inspection services through HouseMaster. HouseMaster of Southwest Michigan is proud to be offering Heroes discounts on home inspections.
      </p>
    </div>
    <div class="clearfix"></div>
    <hr class="company-news__breaker">
  </div>
  <div class="company-news-event <%= hidden %>">
    <div class="col-xs-3">
      <div style="background-image: url(https://s3-us-west-2.amazonaws.com/hm-com/static/-yBcMHWspiO86LINSVRfww/deseretnews.jpg);" class="company-news-event__image"></div>
    </div>
    <div class="col-xs-9">
      <h3 class="company-news-event__date">January 1, 2015</h3>
      <p class="company-news-event__text">
        Certified and trained home inspector Nathan Brimhall from HouseMaster Home Inspections has seen it all. "Foundation issues, electric, plumbing, heating, air conditioning," says Brimhall.
      </p>
    </div>
    <div class="clearfix"></div>
    <hr class="company-news__breaker">
  </div>

  <% if hidden != 'show' %>
    <button class="company-news__show-all show-hide-button" data-target=".company-news-event.toggle">SHOW ALL</button>
  <% end %>
</section>

app/views/company/_press.html.erb
<section class="col-xs-12 company-press">
  <h2 class="company-press__title">PRESS RELEASES</h2>
  <hr class="company-press__breaker">

  <% hidden = 'show' # hidden = 'hidden toggle' if hidding %>
  <div class="company-press-event <%= hidden %>">
    <h3 class="company-press-event__date">January 15, 2015</h3>
    <p class="company-press-event__text">
      HouseMaster, the first and most experienced home inspection franchise company in North America, recently honored Fred Holwell of the local Paradise, NL franchise with the Market Penetration Award at the company's annual conference held October 16-18 at the Charleston Marriot.
    </p>
    <hr class="company-press__breaker">
  </div>

  <div class="company-press-event <%= hidden %>">
    <h3 class="company-press-event__date">January 5, 2015</h3>
    <p class="company-press-event__text">
      HouseMaster, the first and one of the largest home inspection franchise companies in North America, has announced lifelong resident, Kelly Murphy, will now offer professional, guaranteed HouseMaster Home Inspection Services in the Corridor area including the town of Iowa City and Cedar Rapids.
    </p>
    <hr class="company-press__breaker">
  </div>

  <% if hidden != 'show' %>
    <button class="company-press__show-all show-hide-button" data-target=".company-press-event.toggle">SHOW ALL</button>
  <% end %>
</section>

app/views/company/_sidenav.html.erb
<section class="row no-gutters company-side hidden-xs hidden-sm">
  <div class="company-side__breaker"></div>
  <ul class="company-side-nav">
    <li>
      <%= link_to 'PRESS RELEASES', company_path(:anchor => 'press'), :class => 'company-side-nav__link' %>
    </li>
    <li>
      <%= link_to 'IN THE NEWS', company_path(:anchor => 'newsroom'), :class => 'company-side-nav__link' %>
    </li>
    <li>
      <%= link_to 'AWARDS', company_path(:anchor => 'awards'), :class => 'company-side-nav__link' %>
    </li>
    <li>
      <%= link_to 'MEDIA ASSETS', company_path(:anchor => 'media_assets'), :class => 'company-side-nav__link' %>
    </li>
    <!-- <li> -->
    <!--   <%#= link_to 'CONTACT', company_path(:anchor => 'contact_us'), :class => 'company&#45;side&#45;nav__link' %> -->
    <!-- </li> -->
  </ul>
</section>

app/views/company/index.html.erb
<div class="company-sections">
  <span id="press" class="anchor-id"></span>
  <div class="row no-gutters">
    <div class="col-sm-offset-1 col-sm-10">
      <%= render :partial => 'press' %>
    </div>
  </div>

  <span id="newsroom" class="anchor-id"></span>
  <div class="row no-gutters">
    <div class="col-sm-offset-1 col-sm-10">
      <%= render :partial => 'newsroom' %>
    </div>
  </div>

  <span id="awards" class="anchor-id"></span>
  <div class="row no-gutters">
    <div class="col-sm-offset-1 col-sm-10">
      <%= render :partial => 'awards' %>
    </div>
  </div>

  <span id="media_assets" class="anchor-id"></span>
  <div class="row no-gutters">
    <div class="col-sm-offset-1 col-sm-10">
      <%= render :partial => 'media_assets' %>
    </div>
  </div>
</div>